// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'da'
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'hu'
	| 'id'
	| 'ja'
	| 'ko'
	| 'ms'
	| 'nl'
	| 'no'
	| 'pl'
	| 'pt'
	| 'ro'
	| 'ru'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	command: string
	noActiveFile: string
	imageExportPreview: string
	copiedSuccess: string
	copy: string
	copyFail: string
	notAllowCopy: RequiredParams<'format'>
	save: string
	saveSuccess: RequiredParams<'filePath'>
	saveFail: string
	saveVault: string
	includingFilename: string
	imageWidth: string
	exportImage: string
	exportSelectionImage: string
	exportFolder: string
	loading: string
	invalidWidth: string
	resolutionMode: string
	moreSetting: string
	guide: string
	copyNotAllowed: string
	exportAll: string
	noMarkdownFile: string
	selectAll: string
	setting: {
		title: string
		imageWidth: {
			label: string
			description: string
		}
		padding: {
			title: string
			description: string
			top: string
			right: string
			bottom: string
			left: string
		}
		split: {
			title: string
			mode: {
				label: string
				description: string
				none: string
				fixed: string
				hr: string
				auto: string
			}
			height: {
				label: string
				description: string
			}
			overlap: {
				label: string
				description: string
			}
		}
		filename: {
			label: string
			description: string
		}
		resolutionMode: {
			label: string
			description: string
		}
		metadata: {
			label: string
		}
		format: {
			title: string
			description: string
			png0: string
			png1: string
			jpg: string
			pdf: string
		}
		quickExportSelection: {
			label: string
			description: string
		}
		userInfo: {
			title: string
			show: string
			avatar: {
				title: string
				description: string
			}
			name: string
			position: string
			remark: string
			align: string
			removeAvatar: string
		}
		watermark: {
			title: string
			enable: {
				label: string
				description: string
			}
			type: {
				label: string
				description: string
				text: string
				image: string
			}
			text: {
				content: string
				fontSize: string
				color: string
			}
			image: {
				src: {
					label: string
					upload: string
					select: string
				}
			}
			opacity: string
			rotate: string
			width: string
			height: string
			x: string
			y: string
		}
		preview: string
		reset: string
		recursive: string
	}
	imageSelect: {
		search: string
		select: string
		cancel: string
		empty: string
	}
	confirm: string
	cancel: string
	imageUrl: string
	splitInfo: RequiredParams<'pages' | 'rootHeight' | 'splitHeight'>
	splitInfoHr: RequiredParams<'pages' | 'rootHeight'>
}

export type TranslationFunctions = {
	command: () => LocalizedString
	noActiveFile: () => LocalizedString
	imageExportPreview: () => LocalizedString
	copiedSuccess: () => LocalizedString
	copy: () => LocalizedString
	copyFail: () => LocalizedString
	notAllowCopy: (arg: { format: unknown }) => LocalizedString
	save: () => LocalizedString
	saveSuccess: (arg: { filePath: string }) => LocalizedString
	saveFail: () => LocalizedString
	saveVault: () => LocalizedString
	includingFilename: () => LocalizedString
	imageWidth: () => LocalizedString
	exportImage: () => LocalizedString
	exportSelectionImage: () => LocalizedString
	exportFolder: () => LocalizedString
	loading: () => LocalizedString
	invalidWidth: () => LocalizedString
	resolutionMode: () => LocalizedString
	moreSetting: () => LocalizedString
	guide: () => LocalizedString
	copyNotAllowed: () => LocalizedString
	exportAll: () => LocalizedString
	noMarkdownFile: () => LocalizedString
	selectAll: () => LocalizedString
	setting: {
		title: () => LocalizedString
		imageWidth: {
			label: () => LocalizedString
			description: () => LocalizedString
		}
		padding: {
			title: () => LocalizedString
			description: () => LocalizedString
			top: () => LocalizedString
			right: () => LocalizedString
			bottom: () => LocalizedString
			left: () => LocalizedString
		}
		split: {
			title: () => LocalizedString
			mode: {
				label: () => LocalizedString
				description: () => LocalizedString
				none: () => LocalizedString
				fixed: () => LocalizedString
				hr: () => LocalizedString
				auto: () => LocalizedString
			}
			height: {
				label: () => LocalizedString
				description: () => LocalizedString
			}
			overlap: {
				label: () => LocalizedString
				description: () => LocalizedString
			}
		}
		filename: {
			label: () => LocalizedString
			description: () => LocalizedString
		}
		resolutionMode: {
			label: () => LocalizedString
			description: () => LocalizedString
		}
		metadata: {
			label: () => LocalizedString
		}
		format: {
			title: () => LocalizedString
			description: () => LocalizedString
			png0: () => LocalizedString
			png1: () => LocalizedString
			jpg: () => LocalizedString
			pdf: () => LocalizedString
		}
		quickExportSelection: {
			label: () => LocalizedString
			description: () => LocalizedString
		}
		userInfo: {
			title: () => LocalizedString
			show: () => LocalizedString
			avatar: {
				title: () => LocalizedString
				description: () => LocalizedString
			}
			name: () => LocalizedString
			position: () => LocalizedString
			remark: () => LocalizedString
			align: () => LocalizedString
			removeAvatar: () => LocalizedString
		}
		watermark: {
			title: () => LocalizedString
			enable: {
				label: () => LocalizedString
				description: () => LocalizedString
			}
			type: {
				label: () => LocalizedString
				description: () => LocalizedString
				text: () => LocalizedString
				image: () => LocalizedString
			}
			text: {
				content: () => LocalizedString
				fontSize: () => LocalizedString
				color: () => LocalizedString
			}
			image: {
				src: {
					label: () => LocalizedString
					upload: () => LocalizedString
					select: () => LocalizedString
				}
			}
			opacity: () => LocalizedString
			rotate: () => LocalizedString
			width: () => LocalizedString
			height: () => LocalizedString
			x: () => LocalizedString
			y: () => LocalizedString
		}
		preview: () => LocalizedString
		reset: () => LocalizedString
		recursive: () => LocalizedString
	}
	imageSelect: {
		search: () => LocalizedString
		select: () => LocalizedString
		cancel: () => LocalizedString
		empty: () => LocalizedString
	}
	confirm: () => LocalizedString
	cancel: () => LocalizedString
	imageUrl: () => LocalizedString
	splitInfo: (arg: { pages: unknown, rootHeight: unknown, splitHeight: unknown }) => LocalizedString
	splitInfoHr: (arg: { pages: unknown, rootHeight: unknown }) => LocalizedString
}

export type Formatters = Record<string, never>
